<link href="{!!asset('vendors/bootstrap/dist/css/bootstrap.min.css')!!}" rel="stylesheet">
<link href="{!!asset('vendors/font-awesome/css/font-awesome.min.css')!!}" rel="stylesheet">
<link href="{!!asset('vendors/nprogress/nprogress.css')!!}" rel="stylesheet">
<link href="{!!asset('vendors/iCheck/skins/flat/green.css')!!}" rel="stylesheet">
<link href="{!!asset('vendors/google-code-prettify/bin/prettify.min.css')!!}" rel="stylesheet">
<link href="{!!asset('vendors/select2/dist/css/select2.min.css')!!}" rel="stylesheet">
<link href="{!!asset('vendors/switchery/dist/switchery.min.css')!!}" rel="stylesheet">
<link href="{!!asset('vendors/starrr/dist/starrr.css')!!}" rel="stylesheet">
<link href="{!!asset('vendors/bootstrap-daterangepicker/daterangepicker.css')!!}" rel="stylesheet">
<link href="{!!asset('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css')!!}" rel="stylesheet">
<link href="{!!asset('vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css')!!}" rel="stylesheet">
<link href="{!!asset('vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css')!!}" rel="stylesheet">
<link href="{!!asset('vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css')!!}" rel="stylesheet">
<link href="{!!asset('vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css')!!}" rel="stylesheet">
<link href="{!!asset('build/css/custom.min.css')!!}" rel="stylesheet">
<link href="{!!asset('public/assets/styles.css')!!}" rel="stylesheet">